### ISSUE TITLE
has name been dropped from data files ?

### ISSUE THREAD

**Issue by SteveBosley** [ofrohn/ofrohn.github.io#1]
Hi
I've been using three of your excellent data files for a couple of months to help generate sky maps showing meteor radiants.

I tried to run my r script yesterday and it failed - has something changed ?

The relevant bit of my script is …
url3 <<- "https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/stars.6.json"
# Read in the stars way data using the st_read function
stars_sf <<- st_read(url3,stringsAsFactors = FALSE)
      ##########################################################################
## Extract data for chart        ##########################################################################
# Extract the constellation stars with names
stars_con_sf <<- filter(stars_sf,name != "" & con != "")

This is failing with the following error …
Error: Evaluation error: object 'name' not found.

The same script worked fine in mid February 
any ideas ?
Steve Bosley

**Comment by ofrohn** [comment]
It is indeed gone from the main stellar data files. For the possibility to include names in other languages I decided not to replicate the whole naming stuff in every file but to outsource it into a separate file starnames.json, indexed by every star's Hipparcos number.

If you just need the name, use starnames.json, if you need all the data, you can revert to an older version by replacing above url with
https://raw.githubusercontent.com/ofrohn/d3-celestial/v0.6.25/data/stars.6.json
which gave a 500 server error when I just tried.
Well, the data file is in the celestial0.6.zip in this folder 
https://github.com/ofrohn/d3-celestial/tree/master/dist
if you simply want to host it yourself. If you can't, tell me and I'll put it on my github.io site

**Comment by SteveBosley** [comment]
Many thanks - I'll try those to see which works best for me …. self hosting may be the best option in the long term.
